### ISSUE TITLE
disable snap scroll on mobile (or when not supported)

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#69]

**Comment by moritzebeling** [comment]
```css
@supports (display: grid) {
  div {
    display: grid;
  }
}
@supports not (display: grid) {
  div {
    float: right;
  }
}
```
