### ISSUE TITLE
max hight archive mobile

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/svelte-website#70]

**Comment by moritzebeling** [comment]
```css
@supports (display: grid) {
  div {
    display: grid;
  }
}
@supports not (display: grid) {
  div {
    float: right;
  }
}
```
